version: "3"
services:
  api:
    container_name: api
    build: .
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
    networks:
      net:
        ipv4_address: 172.18.1.1

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
